# Generated by Django 5.1.7 on 2025-04-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('moviename', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
